config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    resources :comments
  end
  devise_for :users
  root to: "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Association
  belongs_to :user
  belongs_to :tweet, counter_cache: :comments_counter
  # Validations
  validates :body, presence: true, length: { maximum: 140 }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :comments, dependent: :destroy
  # Validations
  validates :body, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  # Associations
  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Validations
  validates :email, :username, :name, presence: true
  validates :email, :username, uniqueness: true
  validates :email,
            format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/,
                      message: "must have an email format" }
  validates :encrypted_password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username name avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username name avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit update destroy]

  # GET /comments
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  def show; end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit; end

  # POST /comments
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.tweet_id = params["tweet_id"]

    if @comment.save
      redirect_to tweet_path(params["tweet_id"]), notice: "Comment was successfully created."
    else
      redirect_to tweet_path(params["tweet_id"]), status: :unprocessable_entity
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to tweet_path(@comment.tweet.id), notice: "Comment was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    redirect_to tweet_path(@comment.tweet.id), notice: "Comment was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[show destroy edit update]

  # GET /tweets
  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end

  # GET /tweets/1
  def show
    @new_comment = Comment.new
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit; end

  # POST /tweets
  def create
    @tweet = Tweet.new
    @tweet.body = params["body"]
    @tweet.user = current_user
    if @tweet.save
      redirect_to tweets_path, notice: "Tweet created"
    else
      render tweets_path, notice: "Tweet could not be created", status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tweets/1
  def update
    if @tweet.update(tweet_params)
      redirect_to root_path, notice: "Tweet successfully updated"
    else
      render :edit, notice: "Tweet could not be updated", status: :unprocessable_entity
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet.destroy
    redirect_to tweets_url, notice: "Tweet was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def errors_for(record, attribute)
  #   errors = record.errors.full_messages_for(attribute).map do |message|
  #     content_tag(:span, message)
  #   end

  #   safe_join(errors)
  # end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>Tweet:</strong>
    <%= comment.tweet_id %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= comment.body %>
  </p>

</div>

app/views/comments/_form-comment.html.erb
<section class="form__container center-form">
  <%= form_with(model: [Tweet.find(comment.tweet.id), comment]) do |form| %>
    <% if comment.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
          <% comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :body, style: "display: block" %>
      <%= form.text_area :body, class:"input" %>
    </div>

    <div class="center-button">
      <%= form.submit "Edit", class:"edit-tw-comm-button" %>
    </div>
  <% end %>
</section>

app/views/comments/_form.html.erb
<%= form_with(model: [Tweet.find(comment.tweet.id), comment]) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<header class="header">
  <h1 class="heading">Edit comment</h1>
</header>

<%= render "form-comment", comment: @comment %>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form-comment", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetableIndividual</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="body">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/tweets/_create-comment.html.erb
<%= form_with(model: [tweet, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="comment-form__container">

    <%= form.text_area :body, placeholder: "Remember to think before write...", class:"comment-form" %>
  </div>

  <div>
    <%= form.submit "Comment" , class:"comment-button" %>
  </div>
<% end %>

app/views/tweets/_form.html.erb
<p style="color: green"><%= notice %></p>

  <%= form_with(model: tweet, method: :post) do |f| %> 

  <div >
    <div data-turbo="false" class="tweet-form__container">
      <%= f.text_area :body, placeholder: "Remember to think before write...",
      autofocus: true, class:"tweet-form"%>
        <%= f.submit "Tweet", class:"tweet-button" %>
    </div>

  </div>

  <% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <strong>Body:</strong>
    <%= tweet.body %>
  </p>

  <p>
    <strong>Comments counter:</strong>
    <%= tweet.comments_counter %>
  </p>

  <p>
    <strong>User:</strong>
    <%= tweet.user_id %>
  </p>

</div>

app/views/tweets/edit.html.erb
<header class="header">
  <h1 class="heading">Edit Tweet</h1>
</header>

<section class="form__container center-form">
<%= form_with(model: @tweet, method: :patch) do |f| %> 

  <div>
    <%= f.label :body%><br />
    <%= f.text_area :body, placeholder: "Remember to thing before write...",
    autofocus: true, class:"input" %><br>
    <div class="center-button">
      <%= f.submit "Edit", class:"edit-tw-comm-button" %>
    </div>
      
  </div>

<% end %>
</section>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<nav class="nav-bar">
  <% if user_signed_in? %>
    <%= link_to "Edit Profile", edit_user_registration_path, class:"edit-profile-link" %>
    <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: "false" }, class:"delete-profile-link" %>
  <% else %>
    <%= link_to "Log in", new_user_session_path, class:"login-profile-link" %>
  <% end %>
</nav>

<header class="header">
  <h1 class="heading">Home</h1>
</header>

<%if user_signed_in? %>
  <%= render "form", tweet: @new_tweet %>
<%end%>

<div class="tweets">
  <% @tweets.each do |tweet| %>
  <div class="tweet-container">
    <figure class="tweet-avatar__container">
      <% if tweet.user.avatar.attached? %>
        <%= image_tag tweet.user.avatar, class:"tweet-avatar" %>
      <% else %>
        <%= image_tag "default-avatar.jpg", class:"tweet-avatar" %>
      <% end %>
    </figure>
    <div class="tweet-content">
      <div class="tweet-header">
        <%= tweet.user.name %>
        <%= tweet.user.username %>
        <%= time_ago_in_words(tweet.updated_at) %>
      </div>
      <div class="tweet-body">
        <p>
          <%= tweet.body %>
        </p>
      </div>
      <div class="tweet-crud">
        <div>
          <%= link_to tweet_path(tweet) do %>
            <%= image_tag "comment-icon.svg"%>
          <% end %>
          <%= tweet.comments_counter %>
        </div>
        <%if user_signed_in? && current_user.id == tweet.user.id %>
          <div class="tweet-crud__del-upd">
            <%= button_to tweet_path(tweet), method: :delete, data: { turbo: "false" } do %>
              <%= image_tag "delete-icon.svg"%>
            <% end %>
            <%= link_to edit_tweet_path(tweet) do %>
              <%= image_tag "edit-icon.svg"%>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<nav class="nav-bar">
  <% if user_signed_in? %>
    <%= link_to "Edit Profile", edit_user_registration_path, class:"edit-profile-link"%>
    <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: "false" }, class:"delete-profile-link" %>
  <% else %>
    <%= link_to "Log in", new_user_session_path, class:"login-profile-link" %>
  <% end %>
</nav>

<header class="header">
  <h1 class="heading">Tweet Details</h1>
</header>

<div class="tweet-container">
  <figure class="tweet-avatar__container">
    <% if @tweet.user.avatar.attached? %>
      <%= image_tag @tweet.user.avatar, class:"tweet-avatar"  %>
    <% else %>
      <%= image_tag "default-avatar.jpg", class:"tweet-avatar"%>
    <% end %>
  </figure>
  <div class="tweet-content">
    <div class="tweet-header">
      <%= @tweet.user.name %>
      <%= @tweet.user.username %>
      <%= time_ago_in_words(@tweet.updated_at) %>
    </div>
    <div class="tweet-body">
      <p class="tweet-body-p">
        <%= @tweet.body %>
      </p>
    </div>
    <div class="tweet-crud">
      <div>
        <%= link_to tweet_path(@tweet) do %>
          <%= image_tag "comment-icon.svg"%>
        <% end %>
        <%= @tweet.comments_counter %>
      </div>
      <%if user_signed_in? && current_user.id == @tweet.user.id %>
        <div class="tweet-crud__del-upd">
          <%= button_to tweet_path(@tweet), method: :delete, data: { turbo: "false" } do %>
            <%= image_tag "delete-icon.svg"%>
          <% end %>
          <%= link_to edit_tweet_path(@tweet) do %>
            <%= image_tag "edit-icon.svg"%>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%if user_signed_in? %>
  <%= render "create-comment", tweet: @tweet, comment: @new_comment %>
<%end%>

<div class="comments">
  <% @tweet.comments.each do |comment| %>
    <div class="comment-container">
      <figure class="comment-avatar__container">
        <% if comment.user.avatar.attached? %>
          <%= image_tag comment.user.avatar, class:"comment-avatar"  %>
        <% else %>
          <%= image_tag "default-avatar.jpg", class:"comment-avatar"%>
        <% end %>
      </figure>
      <div class="comment-content">
        <div class="comment-header">
          <%= comment.user.name  %>
          <%= comment.user.username  %>
          <%= time_ago_in_words(comment.created_at) %>
        </div>
        <div class="comment-body">
          <p>
        <%= comment.body %>
          </p>
        </div>
        <div class="comment-crud">
          <%if user_signed_in? && current_user.id == comment.user.id %>
            <div class="comment-crud__del-upd">
              <%= button_to tweet_comment_path(@tweet, comment), method: :delete, data: { turbo: "false" } do %>
                <%= image_tag "delete-icon.svg"%>
              <% end %>
              <%= link_to edit_tweet_comment_path(@tweet, comment) do %>
                <%= image_tag "edit-icon.svg"%>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>